### ISSUE TITLE
Will the code be released？

### ISSUE THREAD

**Issue by meyiao** [0xfaded/pislam#1]
Wow，wonderful job！
Please contact with me.jinaqiaoqiao@gmail.com

**Comment by 0xfaded** [comment]
Hi, your email address is bouncing.

I still plan to release the code but am first integrating it with ORBslam. By itself the code is not very useful, it's just an ORB extractor. It's also very specific to the RaspberryPi since the assembly targets Armv7 and not AArch64.

What is your use case?
