### ISSUE TITLE
opengles2 shader for convolution

### ISSUE THREAD

**Issue by kiran4399** [0xfaded/pislam#3]
It would be nice if you have an opengles2 shader code for the gaussian smoothing to get the downsampled images.

Also, when are you planning to release the feature matching code?

**Comment by 0xfaded** [comment]
Feature matching was done using flann. The mentioned testing was throwaway code.

For down sampling, enough people asked me for NEON implementations I've gone and done them. I need to finish up some testing plus add them to the demo.
