### ISSUE TITLE
GTest issues

### ISSUE THREAD

**Issue by meyiao** [0xfaded/pislam#4]
Hi, 
I have installed GTest, but when 'make', errors occur like this:
pislam/test/GaussianTest.cpp:15:53: error: 'tuple' is not a member of ''testing
class GaussianTest: public :: testing::TestWithParam<::testing::tuple<int,int>>{};
I'm not familiar with GTest. Could you guide me how to fix it?

**Comment by 0xfaded** [comment]
I'm also not very familiar with gtest. How did you install it? From github?

Everything works for me on a raspberrypi using gcc version 4.9.2 (Raspbian 4.9.2-10)

**Comment by meyiao** [comment]
For me, replace "::testing::tuple" with "std::tuple", and "::testing::get()" with "std::get()" done the job!
